# Generated by Django 5.1.5 on 2025-01-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_last_name_adminprofile_lastname_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='created_courses',
            field=models.ManyToManyField(blank=True, related_name='professors', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
    ]
